### ISSUE TITLE
Accessing S3 data fails with "HeadObject operation: Forbidden"

### ISSUE THREAD

**Issue by julian-risch** [ZurichNLP/20Minuten#1]
Thanks for creating this repository! I am having problems accessing the data no matter whether I run `aws configure` or use command line arguments to set access-key-id and secret-key. It fails with the following error message when trying to download the file from S3:
`botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`
Could that be a problem of missing read permissions for the uploaded file as indicated [here](https://stackoverflow.com/questions/36144757/aws-cli-s3-a-client-error-403-occurred-when-calling-the-headobject-operation)?

@nicolasspring could you please help here? Thank you!

**Comment by nicolasspring** [comment]
Hi @julian-risch, thanks for bringing this problem to our attention. It seems that there is indeed a problem with the permissions for this specific key. We will get back to you as soon as possible.

**Comment by krupper** [comment]
@nicolasspring Do you have an update regarding the permission problem? Looking forward to use the dataset :-)

**Comment by nicolasspring** [comment]
Thank you for your patience, @julian-risch @krupper. We were now able to make the data available publicly without any restrictions to permissions. Could you kindly confirm that the download with the updated script is now working for you?

**Comment by julian-risch** [comment]
Downloading works now, thank you! 👍 Maybe you could also add a brief description of the dataset here in the repository. At least describing the data format a bit. What are the different files, etc. That would be very helpful! 🙂
